language: elixir

elixir:
  - 1.5
  - 1.4

otp_release:
  - 20.0
  - 19.3
  - 18.3

env:
  global:
    - MIX_ENV=test

notifications:
  email: false

sudo: false

script:
  - mix compile --warnings-as-errors
  - mix test
